//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA_CENSO_INSTRUCTORES.sigrhuProd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sigrhuProd.IsGenerico")]
    public interface IsGenerico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/DoWork", ReplyAction="http://tempuri.org/IsGenerico/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/DoWork", ReplyAction="http://tempuri.org/IsGenerico/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/EjecutarProcedimiento", ReplyAction="http://tempuri.org/IsGenerico/EjecutarProcedimientoResponse")]
        int EjecutarProcedimiento(string nombreprocedimiento, string[] arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/EjecutarProcedimiento", ReplyAction="http://tempuri.org/IsGenerico/EjecutarProcedimientoResponse")]
        System.Threading.Tasks.Task<int> EjecutarProcedimientoAsync(string nombreprocedimiento, string[] arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoSinArg", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoSinArgResponse")]
        System.Data.DataTable ListarGenericoSinArg(string nombreprocedimiento, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoSinArg", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoSinArgResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoSinArgAsync(string nombreprocedimiento, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgEntero", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgEnteroResponse")]
        System.Data.DataTable ListarGenericoArgEntero(string nombreprocedimiento, long arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgEntero", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgEnteroResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgEnteroAsync(string nombreprocedimiento, long arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgCadena", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgCadenaResponse")]
        System.Data.DataTable ListarGenericoArgCadena(string nombreprocedimiento, string arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgCadena", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgCadenaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgCadenaAsync(string nombreprocedimiento, string arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgFecha", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgFechaResponse")]
        System.Data.DataTable ListarGenericoArgFecha(string nombreprocedimiento, System.DateTime arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgFecha", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgFechaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgFechaAsync(string nombreprocedimiento, System.DateTime arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgArregloCadena", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgArregloCadenaResponse")]
        System.Data.DataTable ListarGenericoArgArregloCadena(string nombreprocedimiento, string[] arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/ListarGenericoArgArregloCadena", ReplyAction="http://tempuri.org/IsGenerico/ListarGenericoArgArregloCadenaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgArregloCadenaAsync(string nombreprocedimiento, string[] arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/EjecutarProcedimientoArgArregloCadend", ReplyAction="http://tempuri.org/IsGenerico/EjecutarProcedimientoArgArregloCadendResponse")]
        bool EjecutarProcedimientoArgArregloCadend(string nombreprocedimiento, string[] arg, string cadenaencript);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsGenerico/EjecutarProcedimientoArgArregloCadend", ReplyAction="http://tempuri.org/IsGenerico/EjecutarProcedimientoArgArregloCadendResponse")]
        System.Threading.Tasks.Task<bool> EjecutarProcedimientoArgArregloCadendAsync(string nombreprocedimiento, string[] arg, string cadenaencript);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsGenericoChannel : SISTEMA_CENSO_INSTRUCTORES.sigrhuProd.IsGenerico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsGenericoClient : System.ServiceModel.ClientBase<SISTEMA_CENSO_INSTRUCTORES.sigrhuProd.IsGenerico>, SISTEMA_CENSO_INSTRUCTORES.sigrhuProd.IsGenerico {
        
        public IsGenericoClient() {
        }
        
        public IsGenericoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsGenericoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsGenericoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsGenericoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int EjecutarProcedimiento(string nombreprocedimiento, string[] arg, string cadenaencript) {
            return base.Channel.EjecutarProcedimiento(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Threading.Tasks.Task<int> EjecutarProcedimientoAsync(string nombreprocedimiento, string[] arg, string cadenaencript) {
            return base.Channel.EjecutarProcedimientoAsync(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Data.DataTable ListarGenericoSinArg(string nombreprocedimiento, string cadenaencript) {
            return base.Channel.ListarGenericoSinArg(nombreprocedimiento, cadenaencript);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoSinArgAsync(string nombreprocedimiento, string cadenaencript) {
            return base.Channel.ListarGenericoSinArgAsync(nombreprocedimiento, cadenaencript);
        }
        
        public System.Data.DataTable ListarGenericoArgEntero(string nombreprocedimiento, long arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgEntero(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgEnteroAsync(string nombreprocedimiento, long arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgEnteroAsync(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Data.DataTable ListarGenericoArgCadena(string nombreprocedimiento, string arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgCadena(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgCadenaAsync(string nombreprocedimiento, string arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgCadenaAsync(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Data.DataTable ListarGenericoArgFecha(string nombreprocedimiento, System.DateTime arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgFecha(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgFechaAsync(string nombreprocedimiento, System.DateTime arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgFechaAsync(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Data.DataTable ListarGenericoArgArregloCadena(string nombreprocedimiento, string[] arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgArregloCadena(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarGenericoArgArregloCadenaAsync(string nombreprocedimiento, string[] arg, string cadenaencript) {
            return base.Channel.ListarGenericoArgArregloCadenaAsync(nombreprocedimiento, arg, cadenaencript);
        }
        
        public bool EjecutarProcedimientoArgArregloCadend(string nombreprocedimiento, string[] arg, string cadenaencript) {
            return base.Channel.EjecutarProcedimientoArgArregloCadend(nombreprocedimiento, arg, cadenaencript);
        }
        
        public System.Threading.Tasks.Task<bool> EjecutarProcedimientoArgArregloCadendAsync(string nombreprocedimiento, string[] arg, string cadenaencript) {
            return base.Channel.EjecutarProcedimientoArgArregloCadendAsync(nombreprocedimiento, arg, cadenaencript);
        }
    }
}
